services:

  backend:
    build:
      context: backend
      target: development
    ports:
      - ${BACKEND_PORT:-8051}:8000
    environment:
      - ENV=development
    develop:
      watch:
        - action: sync
          path: backend/
          target: /app
          ignore:
            - __pycache__/
        
        - action: rebuild
          path: backend/requirements.txt
  frontend:
    build:
      context: frontend
      target: dev
    ports:
      - ${FRONTEND_PORT:-8050}:5173
    develop:
      watch:
        - action: sync
          path: frontend/
          target: /app
          ignore:
            - node_modules/
         
        - action: rebuild
          path: frontend/package.json