services:

  backend:
    build:
      context: backend
      target: development
    ports:
      - 8051:8000
    environment:
      - ENV=development
    env_file:
      - .env
    develop:
      watch:
        - action: sync
          path: backend/
          target: /app
          ignore:
            - __pycache__/
        
        - action: rebuild
          path: backend/pyproject.toml
  frontend:
    build:
      context: frontend
      target: dev
      args:
        VITE_API_URL: ${HOST}
    ports:
      - 8050:5173
    develop:
      watch:
        - action: sync
          path: frontend/
          target: /app
          ignore:
            - node_modules/
         
        - action: rebuild
          path: frontend/package.json